version: "3"
services:
  demo:
    restart: always
    build:
      context: .
    volumes:
      - .:/build
    tty: true
    ports:
      - 3000:3000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=index.py
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    command: flask run --host=0.0.0.0 --port 3000